const data = [{
    Name: "Lucky",
    Type: 'Dog',
    Age: 10,
    Breed: 'Pug',
    Notes: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In dapibus fringilla quam, in sagittis nibh vehicula eget. Fusce non ante ac purus sodales aliquet vel vel turpis. Quisque ultricies eleifend ipsum, quis cursus nulla maximus quis. Morbi sollicitudin facilisis libero, ullamcorper pretium magna mattis vel. Ut et tellus ac justo sagittis sodales quis sed nisl. Nulla imperdiet ornare sapien eget viverra. Curabitur accumsan a ipsum a faucibus. Nunc lobortis tincidunt neque.',
    BreedInfo: '',
    DogFriendly: true,
    CatFriendly: true,
    KidFriendly: true,
    Image: 'https://i1.wp.com/nypost.com/wp-content/uploads/sites/2/2020/04/pugs-coronavirus.jpg?quality=80&strip=all&ssl=1',
    SponsorName: "Fast Company",
    SponsorImage: 'https://disabilityin.org/wp-content/uploads/2019/07/fast-company-logo-vector.png',
    SponsorUrl: 'https://www.fastcompany.com/',
},
{
    Name: "Lucky",
    Type: 'Dog',
    Age: 10,
    Breed: 'Pug',
    Notes: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In dapibus fringilla quam, in sagittis nibh vehicula eget. Fusce non ante ac purus sodales aliquet vel vel turpis. Quisque ultricies eleifend ipsum, quis cursus nulla maximus quis. Morbi sollicitudin facilisis libero, ullamcorper pretium magna mattis vel. Ut et tellus ac justo sagittis sodales quis sed nisl. Nulla imperdiet ornare sapien eget viverra. Curabitur accumsan a ipsum a faucibus. Nunc lobortis tincidunt neque.',
    BreedInfo: '',
    DogFriendly: true,
    CatFriendly: true,
    KidFriendly: true,
    Image: 'https://i1.wp.com/nypost.com/wp-content/uploads/sites/2/2020/04/pugs-coronavirus.jpg?quality=80&strip=all&ssl=1',
    // SponsorName: "Fast Company",
    // SponsorImage: 'https://disabilityin.org/wp-content/uploads/2019/07/fast-company-logo-vector.png',
    // SponsorUrl: 'https://www.fastcompany.com/',
},
{
    Name: "Lucky",
    Type: 'Dog',
    Age: 10,
    Breed: 'Pug',
    Notes: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In dapibus fringilla quam, in sagittis nibh vehicula eget. Fusce non ante ac purus sodales aliquet vel vel turpis. Quisque ultricies eleifend ipsum, quis cursus nulla maximus quis. Morbi sollicitudin facilisis libero, ullamcorper pretium magna mattis vel. Ut et tellus ac justo sagittis sodales quis sed nisl. Nulla imperdiet ornare sapien eget viverra. Curabitur accumsan a ipsum a faucibus. Nunc lobortis tincidunt neque.',
    BreedInfo: '',
    DogFriendly: true,
    CatFriendly: true,
    KidFriendly: true,
    Image: 'https://i1.wp.com/nypost.com/wp-content/uploads/sites/2/2020/04/pugs-coronavirus.jpg?quality=80&strip=all&ssl=1',
    SponsorName: "Fast Company",
    SponsorImage: 'https://disabilityin.org/wp-content/uploads/2019/07/fast-company-logo-vector.png',
    SponsorUrl: 'https://www.fastcompany.com/',
}
]

export default data;